# Generated by Django 5.0.14 on 2026-08-08 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('motif_admission', models.TextField()),
                ('chambre', models.CharField(max_length=20)),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('medecin_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
