# Generated by Django 6.1 on 2026-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.TextField()),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=10)),
                ('motif_annulation', models.TextField(blank=True, default='')),
            ],
        ),
    ]
