# Generated by Django 5.0.14 on 2026-08-08 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_nom', models.CharField(max_length=100)),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('diagnostic_final', models.TextField()),
                ('autorise', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
