# Generated by Django 6.1 on 2026-08-28 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 28, 7, 18, 8, 892747, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
